spring:
  application:
    name: demoservice
server:
  port: 8080

---
spring:
  profiles: dev
  application:
    name: demoservice
server:
  port: 9090

---
spring:
  profiles: prod
  application:
    name: demoservice
server:
  port: 4431

---
spring:
  profiles: ssl
  application:
    name: ssl demoservice
server:
  port: 443
  ssl:
    key-store: keystore.p12
    key-store-password: waxcio
    keyStoreType: PKCS12
    keyAlias: tomcat